spring:
  datasource:
    password: admin123
    url: jdbc:sqlserver://OMARALI\\SQLEXPRESS:1656;databaseName=School;encrypt=true;trustServerCertificate=true;
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        format_sql: true
